### ISSUE TITLE
Update to cpad_2020b

### ISSUE THREAD

**Issue by simonw** [simonw/calands-datasette#4]
There's an updated version out: https://databasin.org/datasets/abfa205da47846389fc094ec0be2b065/

**Comment by simonw** [comment]
First attempt at this failed (even though it deployed): https://github.com/simonw/calands-datasette/runs/1732732550?check_suite_focus=true

```
2021-01-20T05:38:51.7566865Z Usage: shapefile-to-sqlite [OPTIONS] DB_PATH [SHAPEFILE]...
2021-01-20T05:38:51.7567814Z Try 'shapefile-to-sqlite --help' for help.
2021-01-20T05:38:51.7568230Z 
2021-01-20T05:38:51.7569033Z Error: Invalid value for '[SHAPEFILE]...': File 'cpad/CPAD_2020a/CPAD_2020a_Units.shp' does not exist.
2021-01-20T05:38:51.9584172Z Usage: shapefile-to-sqlite [OPTIONS] DB_PATH [SHAPEFILE]...
2021-01-20T05:38:51.9588423Z Try 'shapefile-to-sqlite --help' for help.
2021-01-20T05:38:51.9588918Z 
2021-01-20T05:38:51.9590107Z Error: Invalid value for '[SHAPEFILE]...': File 'cpad/CPAD_2020a/CPAD_2020a_SuperUnits.shp' does not exist.
2021-01-20T05:38:52.3060458Z Traceback (most recent call last):
2021-01-20T05:38:52.3063561Z   File "/opt/hostedtoolcache/Python/3.8.7/x64/bin/sqlite-utils", line 8, in <module>
2021-01-20T05:38:52.3064999Z     sys.exit(cli())
2021-01-20T05:38:52.3066463Z   File "/opt/hostedtoolcache/Python/3.8.7/x64/lib/python3.8/site-packages/click/core.py", line 829, in __call__
2021-01-20T05:38:52.3067678Z     return self.main(*args, **kwargs)
2021-01-20T05:38:52.3069097Z   File "/opt/hostedtoolcache/Python/3.8.7/x64/lib/python3.8/site-packages/click/core.py", line 782, in main
2021-01-20T05:38:52.3070125Z     rv = self.invoke(ctx)
2021-01-20T05:38:52.3072024Z   File "/opt/hostedtoolcache/Python/3.8.7/x64/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
2021-01-20T05:38:52.3073040Z     return _process_result(sub_ctx.command.invoke(sub_ctx))
2021-01-20T05:38:52.3074170Z   File "/opt/hostedtoolcache/Python/3.8.7/x64/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
2021-01-20T05:38:52.3075115Z     return ctx.invoke(self.callback, **ctx.params)
2021-01-20T05:38:52.3076215Z   File "/opt/hostedtoolcache/Python/3.8.7/x64/lib/python3.8/site-packages/click/core.py", line 610, in invoke
2021-01-20T05:38:52.3076949Z     return callback(*args, **kwargs)
2021-01-20T05:38:52.3077996Z   File "/opt/hostedtoolcache/Python/3.8.7/x64/lib/python3.8/site-packages/sqlite_utils/cli.py", line 995, in query
2021-01-20T05:38:52.3078822Z     cursor = db.execute(sql, dict(param))
2021-01-20T05:38:52.3079824Z   File "/opt/hostedtoolcache/Python/3.8.7/x64/lib/python3.8/site-packages/sqlite_utils/db.py", line 226, in execute
2021-01-20T05:38:52.3080746Z     return self.conn.execute(sql, parameters)
2021-01-20T05:38:52.3081568Z sqlite3.OperationalError: no such table: main.CPAD_2020a_SuperUnits
2021-01-20T05:38:52.3947632Z Traceback (most recent call last):
2021-01-20T05:38:52.3949498Z   File "/opt/hostedtoolcache/Python/3.8.7/x64/bin/sqlite-utils", line 8, in <module>
2021-01-20T05:38:52.3950528Z     sys.exit(cli())
2021-01-20T05:38:52.3951860Z   File "/opt/hostedtoolcache/Python/3.8.7/x64/lib/python3.8/site-packages/click/core.py", line 829, in __call__
2021-01-20T05:38:52.3953053Z     return self.main(*args, **kwargs)
2021-01-20T05:38:52.3954484Z   File "/opt/hostedtoolcache/Python/3.8.7/x64/lib/python3.8/site-packages/click/core.py", line 782, in main
2021-01-20T05:38:52.3955559Z     rv = self.invoke(ctx)
2021-01-20T05:38:52.3956865Z   File "/opt/hostedtoolcache/Python/3.8.7/x64/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
2021-01-20T05:38:52.3958096Z     return _process_result(sub_ctx.command.invoke(sub_ctx))
2021-01-20T05:38:52.3959660Z   File "/opt/hostedtoolcache/Python/3.8.7/x64/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
2021-01-20T05:38:52.3960818Z     return ctx.invoke(self.callback, **ctx.params)
2021-01-20T05:38:52.3962286Z   File "/opt/hostedtoolcache/Python/3.8.7/x64/lib/python3.8/site-packages/click/core.py", line 610, in invoke
2021-01-20T05:38:52.3963637Z     return callback(*args, **kwargs)
2021-01-20T05:38:52.3965135Z   File "/opt/hostedtoolcache/Python/3.8.7/x64/lib/python3.8/site-packages/sqlite_utils/cli.py", line 995, in query
2021-01-20T05:38:52.3966230Z     cursor = db.execute(sql, dict(param))
2021-01-20T05:38:52.3967666Z   File "/opt/hostedtoolcache/Python/3.8.7/x64/lib/python3.8/site-packages/sqlite_utils/db.py", line 226, in execute
2021-01-20T05:38:52.3968888Z     return self.conn.execute(sql, parameters)
2021-01-20T05:38:52.3969982Z sqlite3.OperationalError: no such table: main.CPAD_2020a_Units
2021-01-20T05:38:52.4771146Z Error: No such column: ACCESS_TYP
2021-01-20T05:38:52.5607486Z Error: No such column: AGNCY_NAME
2021-01-20T05:38:52.6432355Z Error: No such column: AGNCY_LEV
2021-01-20T05:38:52.7246101Z Error: No such column: AGNCY_TYP
2021-01-20T05:38:52.8064341Z Error: No such column: LAYER
2021-01-20T05:38:52.8887498Z Error: No such column: MNG_AGENCY
2021-01-20T05:38:52.9704033Z Error: No such column: MNG_AG_LEV
2021-01-20T05:38:53.0522100Z Error: No such column: MNG_AG_TYP
2021-01-20T05:38:53.1347774Z Error: No such column: COUNTY
2021-01-20T05:38:53.2174731Z Error: No such column: DES_TP
2021-01-20T05:38:53.3000817Z Error: No such column: ACCESS_TYP
2021-01-20T05:38:53.3829182Z Error: No such column: MNG_AGENCY
2021-01-20T05:38:53.4650811Z Error: No such column: MNG_AG_LEV
2021-01-20T05:38:53.5470485Z Error: No such column: MNG_AG_TYP
2021-01-20T05:38:53.6284524Z Error: No such column: LAYER
2021-01-20T05:38:53.7967017Z Traceback (most recent call last):
2021-01-20T05:38:53.7969543Z   File "/opt/hostedtoolcache/Python/3.8.7/x64/bin/sqlite-utils", line 8, in <module>
2021-01-20T05:38:53.7970761Z     sys.exit(cli())
2021-01-20T05:38:53.7972370Z   File "/opt/hostedtoolcache/Python/3.8.7/x64/lib/python3.8/site-packages/click/core.py", line 829, in __call__
2021-01-20T05:38:53.7973525Z     return self.main(*args, **kwargs)
2021-01-20T05:38:53.7975095Z   File "/opt/hostedtoolcache/Python/3.8.7/x64/lib/python3.8/site-packages/click/core.py", line 782, in main
2021-01-20T05:38:53.7976236Z     rv = self.invoke(ctx)
2021-01-20T05:38:53.7977908Z   File "/opt/hostedtoolcache/Python/3.8.7/x64/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
2021-01-20T05:38:53.7979157Z     return _process_result(sub_ctx.command.invoke(sub_ctx))
2021-01-20T05:38:53.7980799Z   File "/opt/hostedtoolcache/Python/3.8.7/x64/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
2021-01-20T05:38:53.7981952Z     return ctx.invoke(self.callback, **ctx.params)
2021-01-20T05:38:53.7983573Z   File "/opt/hostedtoolcache/Python/3.8.7/x64/lib/python3.8/site-packages/click/core.py", line 610, in invoke
2021-01-20T05:38:53.7987468Z     return callback(*args, **kwargs)
2021-01-20T05:38:53.7988683Z   File "/opt/hostedtoolcache/Python/3.8.7/x64/lib/python3.8/site-packages/sqlite_utils/cli.py", line 480, in enable_fts
2021-01-20T05:38:53.7989409Z     db[table].enable_fts(
2021-01-20T05:38:53.7990509Z   File "/opt/hostedtoolcache/Python/3.8.7/x64/lib/python3.8/site-packages/sqlite_utils/db.py", line 1337, in enable_fts
2021-01-20T05:38:53.7991343Z     self.populate_fts(columns)
2021-01-20T05:38:53.8033098Z   File "/opt/hostedtoolcache/Python/3.8.7/x64/lib/python3.8/site-packages/sqlite_utils/db.py", line 1381, in populate_fts
2021-01-20T05:38:53.8033989Z     self.db.executescript(sql)
2021-01-20T05:38:53.8035359Z   File "/opt/hostedtoolcache/Python/3.8.7/x64/lib/python3.8/site-packages/sqlite_utils/db.py", line 233, in executescript
2021-01-20T05:38:53.8036215Z     return self.conn.executescript(sql)
2021-01-20T05:38:53.8036918Z sqlite3.OperationalError: no such table: CPAD_2020a_Units
2021-01-20T05:38:53.8823971Z Traceback (most recent call last):
2021-01-20T05:38:53.8825974Z   File "/opt/hostedtoolcache/Python/3.8.7/x64/bin/sqlite-utils", line 8, in <module>
2021-01-20T05:38:53.8826977Z     sys.exit(cli())
2021-01-20T05:38:53.8828272Z   File "/opt/hostedtoolcache/Python/3.8.7/x64/lib/python3.8/site-packages/click/core.py", line 829, in __call__
2021-01-20T05:38:53.8829596Z     return self.main(*args, **kwargs)
2021-01-20T05:38:53.8830968Z   File "/opt/hostedtoolcache/Python/3.8.7/x64/lib/python3.8/site-packages/click/core.py", line 782, in main
2021-01-20T05:38:53.8831979Z     rv = self.invoke(ctx)
2021-01-20T05:38:53.8833246Z   File "/opt/hostedtoolcache/Python/3.8.7/x64/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
2021-01-20T05:38:53.8834424Z     return _process_result(sub_ctx.command.invoke(sub_ctx))
2021-01-20T05:38:53.8835862Z   File "/opt/hostedtoolcache/Python/3.8.7/x64/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
2021-01-20T05:38:53.8837129Z     return ctx.invoke(self.callback, **ctx.params)
2021-01-20T05:38:53.8838552Z   File "/opt/hostedtoolcache/Python/3.8.7/x64/lib/python3.8/site-packages/click/core.py", line 610, in invoke
2021-01-20T05:38:53.8839589Z     return callback(*args, **kwargs)
2021-01-20T05:38:53.8841795Z   File "/opt/hostedtoolcache/Python/3.8.7/x64/lib/python3.8/site-packages/sqlite_utils/cli.py", line 480, in enable_fts
2021-01-20T05:38:53.8842788Z     db[table].enable_fts(
2021-01-20T05:38:53.8844081Z   File "/opt/hostedtoolcache/Python/3.8.7/x64/lib/python3.8/site-packages/sqlite_utils/db.py", line 1337, in enable_fts
2021-01-20T05:38:53.8845076Z     self.populate_fts(columns)
2021-01-20T05:38:53.8846381Z   File "/opt/hostedtoolcache/Python/3.8.7/x64/lib/python3.8/site-packages/sqlite_utils/db.py", line 1381, in populate_fts
2021-01-20T05:38:53.8847412Z     self.db.executescript(sql)
2021-01-20T05:38:53.8848757Z   File "/opt/hostedtoolcache/Python/3.8.7/x64/lib/python3.8/site-packages/sqlite_utils/db.py", line 233, in executescript
2021-01-20T05:38:53.8849878Z     return self.conn.executescript(sql)
2021-01-20T05:38:53.8850823Z sqlite3.OperationalError: no such table: CPAD_2020a_SuperUnits
2021-01-20T05:38:53.9801523Z ##[group]Run google-github-actions/setup-gcloud@master
2021-01-20T05:38:53.9802078Z with:
2021-01-20T05:38:53.9802386Z   version: 275.0.0
2021-01-20T05:38:53.9803612Z   service_account_email: ***
2021-01-20T05:38:54.1699548Z   service_account_key: ***
2021-01-20T05:38:54.1700050Z   export_default_credentials: false
2021-01-20T05:38:54.1700451Z env:
2021-01-20T05:38:54.1700944Z   pythonLocation: /opt/hostedtoolcache/Python/3.8.7/x64
2021-01-20T05:38:54.1701606Z   LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.8.7/x64/lib
2021-01-20T05:38:54.1702094Z ##[endgroup]
2021-01-20T05:38:54.7878930Z [command]/bin/tar xz --warning=no-unknown-keyword -C /home/runner/work/_temp/8fc0c455-3f9f-403f-ad1d-35ddd7ac8edd -f /home/runner/work/_temp/e09e8510-58f2-4cd4-b43f-764a183077c8
```
It would have been better if this workflow had failed rather than ignoring those errors.

**Comment by simonw** [comment]
2021a is out now: https://data.cnra.ca.gov/dataset/california-protected-areas-database/resource/2f5efcf0-dffa-4890-92a8-3df3589f0e50

**Comment by simonw** [comment]
Since this will change the table names from `CPAD_2020a_SuperUnits` to `CPAD_2021a_SuperUnits` it will break the demo links in this blog post, so I need to update that too: https://simonwillison.net/2021/Jan/24/drawing-shapes-spatialite/

**Comment by simonw** [comment]
Maybe I should leave the old tables and add new ones? That way I don't break any bookmarked links.

The DB file is 100MB, so bumping it up to 200MB won't really hurt anything.

Or... I could leave https://calands.datasettes.com/calands as-is but add https://calands.datasettes.com/calands-2021a with the new tables. That way there's an entirely fresh database for the new release.
